[project]
name = "echo"
version = "0.0.1"
description = "Library for parsing intents"
authors = [
    {name = "Jozef Steinhübl", email = "contact@xhyrom.dev"},
]
readme = "README.md"
license = {text = "Apache License 2.0"}

[tool.pdm]
distribution = false
